const $=id=>document.getElementById(id);const screens=['pairScreen','mainScreen','chatScreen','settingsScreen'];
const state={token:localStorage.pushToken||'',name:localStorage.displayName||'',backend:'',me:null,people:[],conversation:null,peer:null,messages:[],socket:null,retry:null,poll:null};
const installationId=localStorage.installationId||(localStorage.installationId=crypto.randomUUID());
function screen(id){screens.forEach(name=>$(name).classList.toggle('hidden',name!==id))}
function initials(name='?'){return name.trim().split(/\s+/).slice(0,2).map(v=>v[0]).join('').toUpperCase()}
function esc(value){return String(value).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function toast(text){$('toast').textContent=text;$('toast').classList.remove('hidden');setTimeout(()=>$('toast').classList.add('hidden'),2600)}
function decodeUser(token){try{return JSON.parse(atob(token.split('.')[1].replace(/-/g,'+').replace(/_/g,'/'))).sub}catch{return null}}
function setStatus(id,text,type=''){const el=$(id);el.textContent=text;el.className='status '+type}
async function loadRuntimeConfig(){try{const response=await fetch('config.json',{cache:'no-store'});if(response.ok){const config=await response.json();state.backend=String(config.backendUrl||'').replace(/\/$/,'')}}catch{}if(location.hostname.endsWith('github.io')&&!state.backend)throw new Error('Сервер временно не настроен')}
async function api(path,options={}){const response=await fetch(`${state.backend}${path}`,{...options,headers:{'Content-Type':'application/json',...(state.token?{Authorization:`Bearer ${state.token}`}:{})}});const body=await response.text();if(!response.ok){if(response.status===401&&state.token){logout();throw new Error('Сессия истекла')}let detail='';try{detail=JSON.parse(body).message||''}catch{}throw new Error(detail||`HTTP ${response.status}`)}return body?JSON.parse(body):null}
async function startSession(){state.me=decodeUser(state.token);const me=await api('/api/me');state.name=me.displayName;localStorage.setItem('displayName',state.name);$('settingsButton').textContent=initials(state.name);$('profileAvatar').textContent=initials(state.name);$('profileName').textContent=state.name||'Аккаунт';screen('mainScreen');connectSocket();await loadPeople();clearInterval(state.poll);state.poll=setInterval(()=>state.conversation?loadMessages(false):loadPeople(false),5000)}
async function boot(){if(!('serviceWorker'in navigator))toast('Service Worker недоступен');else navigator.serviceWorker.register('service-worker.js').catch(()=>{});try{await loadRuntimeConfig()}catch(e){screen('pairScreen');setStatus('pairStatus',e.message,'error');return}if(!state.token){screen('pairScreen');return}try{await startSession()}catch(e){screen('pairScreen');setStatus('pairStatus',e.message,'error')}}
async function loadPeople(showError=true){try{state.people=await api('/api/users');renderPeople()}catch(e){if(showError)toast(e.message)}}
function renderPeople(){const root=$('people');root.innerHTML=state.people.length?state.people.map(p=>`<article class="person-row" data-user="${p.id}"><div class="person-avatar">${esc(initials(p.displayName))}</div><div class="person-copy"><h3>${esc(p.displayName)}</h3><p>${p.unreadCount?`${p.unreadCount} непрочитанных`:'Нажмите, чтобы открыть чат'}</p></div>${p.unreadCount?`<span class="badge">${p.unreadCount}</span>`:'<span class="chevron">›</span>'}</article>`).join(''):'<div class="empty">Других пользователей пока нет</div>'}
async function openChat(user){try{state.peer=user;state.conversation=await api(`/api/conversations/user/${user.id}`,{method:'POST',body:'{}'});$('chatName').textContent=user.displayName;$('chatAvatar').textContent=initials(user.displayName);screen('chatScreen');await loadMessages(true);setTimeout(()=>$('messageInput').focus(),250)}catch(e){toast(e.message)}}
async function loadMessages(scroll){if(!state.conversation)return;try{const values=await api(`/api/conversations/${state.conversation.id}/messages?limit=100`);state.messages=values.sort((a,b)=>new Date(a.createdAt)-new Date(b.createdAt));renderMessages(scroll);await api(`/api/conversations/${state.conversation.id}/read`,{method:'POST',body:'{}'});if(state.peer){const found=state.people.find(p=>p.id===state.peer.id);if(found)found.unreadCount=0}}catch(e){toast(e.message)}}
function renderMessages(scroll=false){const root=$('messages');const wasBottom=root.scrollHeight-root.scrollTop-root.clientHeight<90;root.innerHTML=state.messages.length?state.messages.map(m=>{const mine=m.senderId===state.me;const time=new Date(m.createdAt).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'});return `<div class="bubble-row ${mine?'mine':''}" data-message="${m.id}"><div class="bubble"><div class="bubble-text">${esc(m.text)}</div><div class="bubble-meta"><span>${time}</span>${mine?`<span class="checks">${m.status==='READ'?'✓✓':'✓'}</span>`:''}</div></div></div>`}).join(''):'<div class="empty">Начните разговор</div>';if(scroll||wasBottom)requestAnimationFrame(()=>root.scrollTop=root.scrollHeight)}
async function sendMessage(){const input=$('messageInput'),text=input.value.trim();if(!text||!state.conversation)return;input.value='';resizeInput();try{const message=await api(`/api/conversations/${state.conversation.id}/messages`,{method:'POST',body:JSON.stringify({text})});state.messages.push(message);renderMessages(true)}catch(e){input.value=text;resizeInput();toast(e.message)}}
function connectSocket(){if(!state.token)return;clearTimeout(state.retry);const target=new URL(state.backend||location.origin);target.protocol=target.protocol==='https:'?'wss:':'ws:';target.pathname='/ws';target.search=`access_token=${encodeURIComponent(state.token)}`;const ws=new WebSocket(target);state.socket=ws;setConnection(false,'Подключение…');ws.onopen=()=>setConnection(true,'Онлайн');ws.onmessage=event=>{try{const incoming=JSON.parse(event.data);if(incoming.type!=='MESSAGE_CREATED')return;const message=incoming.payload;if(state.conversation?.id===message.conversationId){if(!state.messages.some(m=>m.id===message.id))state.messages.push(message);renderMessages(true);api(`/api/conversations/${state.conversation.id}/read`,{method:'POST',body:'{}'}).catch(()=>{})}else{loadPeople(false)}}catch{}};ws.onclose=()=>{if(state.socket===ws){setConnection(false,'Переподключение…');state.retry=setTimeout(connectSocket,2500)}};ws.onerror=()=>ws.close()}
function setConnection(online,text){$('connectionText').textContent=text;$('connectionDot').classList.toggle('online',online);$('chatState').textContent=online?'онлайн':'соединение…'}
function base64Bytes(value){const clean=value.replace(/=+$/,'');const padding='='.repeat((4-clean.length%4)%4),raw=atob((clean+padding).replace(/-/g,'+').replace(/_/g,'/'));return Uint8Array.from(raw,c=>c.charCodeAt(0))}
async function enablePush(){try{setStatus('pushStatus','Проверяю подписку…');const key=await api('/api/push/vapid-public-key');if(!key.enabled)throw new Error('Уведомления выключены на сервере');const registration=await navigator.serviceWorker.register('service-worker.js');await navigator.serviceWorker.ready;const permission=await Notification.requestPermission();if(permission!=='granted')throw new Error('Разрешение не выдано');let subscription=await registration.pushManager.getSubscription();if(!subscription)subscription=await registration.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:base64Bytes(key.publicKey)});const data=subscription.toJSON();await api('/api/push/subscriptions',{method:'POST',body:JSON.stringify({endpoint:data.endpoint,p256dh:data.keys.p256dh,auth:data.keys.auth})});setStatus('pushStatus','Уведомления включены','ok')}catch(e){setStatus('pushStatus',e.message,'error')}}
function showSettings(){screen('settingsScreen');$('profileName').textContent=state.name||'Аккаунт';$('profileAvatar').textContent=initials(state.name);setStatus('pushStatus',Notification.permission==='granted'?'Системное разрешение выдано':'Нажмите, чтобы включить')}
function logout(){localStorage.removeItem('pushToken');localStorage.removeItem('displayName');state.socket?.close();clearInterval(state.poll);location.reload()}
$('pair').onclick=async()=>{const code=$('code').value.trim();if(!/^\d{8}$/.test(code)){setStatus('pairStatus','Введите восемь цифр','error');return}try{setStatus('pairStatus','Подключаю…');const result=await api('/api/push/pair',{method:'POST',body:JSON.stringify({code,installationId})});state.token=result.token;state.name=result.displayName;localStorage.setItem('pushToken',state.token);localStorage.setItem('displayName',state.name);await startSession()}catch(e){setStatus('pairStatus',e.message,'error')}};
$('people').onclick=e=>{const row=e.target.closest('[data-user]');if(row)openChat(state.people.find(p=>p.id===row.dataset.user))};
$('backButton').onclick=()=>{state.conversation=null;state.peer=null;screen('mainScreen');loadPeople(false)};$('composer').onsubmit=e=>{e.preventDefault();sendMessage()};$('messageInput').oninput=resizeInput;function resizeInput(){const el=$('messageInput');el.style.height='auto';el.style.height=Math.min(el.scrollHeight,110)+'px'}
$('settingsButton').onclick=showSettings;$('settingsTab').onclick=showSettings;$('settingsBack').onclick=()=>screen('mainScreen');$('enablePush').onclick=enablePush;$('logout').onclick=logout;boot();
